version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:9.6
    container_name: keycloak_postgress
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8082:8080
    volumes:
      - ./themes/CAT:/opt/jboss/keycloak/themes/CAT
      - ./startup-scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
    depends_on:
      - postgres
